[package]
name = "bevy_ort"
description = "bevy ort (onnxruntime) plugin"
version = "0.1.0"
edition = "2021"
authors = ["mosure <mitchell@mosure.me>"]
license = "MIT"
keywords = [
  "bevy",
  "ort",
  "onnx",
  "onnxruntime",
]
homepage = "https://github.com/mosure/bevy_ort"
repository = "https://github.com/mosure/bevy_ort"
readme = "README.md"
exclude = [
  ".devcontainer",
  ".github",
  "docs",
  "dist",
  "build",
  "assets",
  "credits",
]

default-run = "modnet"


[dependencies]
bevy_args = "1.3"
ort = "2.0.0-alpha.4"
thiserror = "1.0"
tokio = { version = "1.36", features = ["full"] }


[dependencies.bevy]
version = "0.13"
default-features = false
features = [
  "bevy_asset",
]


[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = 3


[lib]
path = "src/lib.rs"


[[bin]]
name = "modnet"
path = "tools/modnet.rs"

